### ISSUE TITLE
I have added this addon with gravity form but it's not working. 

### ISSUE THREAD

**Issue by itsachalsingh** [razorpay/razorpay-gravity-forms#10]
Here is my website url https://ksasolutionindia.com/social-media-3/ . when i'm submitting the form it display thank you messsage and a button"pay with razo"
![image](https://user-images.githubusercontent.com/36112289/38205423-316da6d0-36c4-11e8-8926-1efa65a3af2d.png)

![image](https://user-images.githubusercontent.com/36112289/38205470-612f05ee-36c4-11e8-9e80-833747ee9eb5.png)

**Comment by captn3m0** [comment]
We use GitHub issues for known issues and feature requests. For support queries, please send us a mail at <integrations@razorpay.com>

**Comment by karthigeyan15** [comment]
this problem resolved or not???? Please tell me
