### ISSUE TITLE
Gravity Form Submit issue

### ISSUE THREAD

**Issue by itsachalsingh** [razorpay/razorpay-gravity-forms#11]
When I use the razorpay addon it will give the 505 error when form is submit.  Where razorpay payment option is not attached. https://ksasolutionindia.com/products/payments/?softwaare_type=Buy&product_name=kcent_account

But where i use  razorpay payment option it will work fine  https://ksasolutionindia.com/branding-marketing/branding-payment/?branding_price=Letterhead

**Comment by saivychawla** [comment]
Error log in this code razorpay-sdk/src/Request.php on line 120
I ahve the same issue

**Comment by karthigeyan15** [comment]
I have same problem how to resolve it please tell me

**Comment by ImPrasadM** [comment]
I am using this Plugin, After submit the gravity form ,before razor payment I am getting a email notification, Can some one please help me I need Email Notification only after successful Payment.

**Comment by saivychawla** [comment]
> I am using this Plugin, After submit the gravity form ,before razor payment I am getting a email notification, Can some one please help me I need Email Notification only after successful Payment.
> 
> Thank You

this plugin first submit the data and then initiate the transaction. Need an update from developer

**Comment by ImPrasadM** [comment]
Please reply anyone, I need Email notification after successful payment.

**Comment by isaumya** [comment]
Please check this reply: https://github.com/razorpay/razorpay-gravity-forms/issues/15#issuecomment-503525415
Then do let me know where do you want to redirect to after the payment?

**Comment by prem-techchefs** [comment]
Note: For proper use of this plugin, you have to give minimum 1INR Rs amount while using gravity form.
