### ISSUE TITLE
how to redirect after the payment completed

### ISSUE THREAD

**Issue by karthigeyan15** [razorpay/razorpay-gravity-forms#14]
how to redirect after the payment is completed

**Comment by isaumya** [comment]
Please check this reply: https://github.com/razorpay/razorpay-gravity-forms/issues/15#issuecomment-503525415
Then do let me know where do you want to redirect to after the payment?

**Comment by prem-techchefs** [comment]
@karthigeyan15  for redirection you can use hook in your function.php file. 

> gform_razorpay_complete_payment
