### ISSUE TITLE
Razor Pay gravity forms Email Notification issue

### ISSUE THREAD

**Issue by ImPrasadM** [razorpay/razorpay-gravity-forms#15]
I am using this Plugin, After submit the gravity form, (before payment with Razor Pay) I am getting a email notification, Can some one please help me I need Email Notification only after Successful Payment.

Thank You.

**Comment by isaumya** [comment]
As the Reazorpay team will not take any responsibility to make quality plugins like PayPal or Stripe, we are left with this half baked plugins which the team barely update or provide support to. Anyways. I have recorded the plugin to add a few features one of them being sending notifications on payment events.

**You can find my project repo here: https://github.com/isaumya/razorpay-gravity-forms-updated**

But please note that the plugin still has many issues and no way close to the quality of a PayPal or stipe plugin. I guess it never will be done if Razorpay Team didn't make a quality plugin themselves. Anyways, hope this helps. 

The unfortunate thing is I truly like Razorpay but can't help but hating their integration support, especially in the WordPress community.

**Comment by ngrhd** [comment]
Thank you very much for your work. I'll test it out later. The biggest issue as per what I've read is the redirection to `Callback is complete.` If this gets sorted out, I'll definitely use it in production.
On the other hand, I'm eagerly waiting for Stripe to launch their services here in India. Will definitely switch in an instant.

**Comment by isaumya** [comment]
@ngrhd well, I've added an extra line on that page saying your order is complete and a hyperlink to go back to the home page. I know it is not good looking but gets the jobs done and the user can easily click on the hyperlink to go back to the home page. Also, by this time the user has already received an email from gravity form. So, in some way, it can be used on a production website. Maybe not the as good looking way as PayPal or Stripe but it will work. Also as I mostly receive international payment, Razorpay costs less than the others.
Now coming to Stripe release in India, well I have some very bad news for you. Though Stripe is going to launch in India by this year, but they have some insanely high charges, making it completely unusable. You might be thinking how the hell do I know that, well, guess what, I have Stripe India private beta invite with me. So, I've checked out Stripe India as well, but man, their price is simply insane. Here are some few points about Stripe India:
- If you want to collect international currency, you need to first get the Import-Export License. You need the IEC number and purpose code during registration.
- You can only take payment via Visa & Mastercard and not Amex or Netbanking or UPI. Only cards.
- For domestic INR payment, you have to pay 2% + 18% GST
- If your amount is in INR and it is being paid by some international card, you have to pay 3% + 18% GST
- If you have IEC code and taking payment in foreign currency like USD or so, you have to pay 4.3% + 2% FX Fee + 18% GST on those fees
- Also currently Stripe India doesn't work with any plugins as Stripe India API is slightly different than the global API and most of the plugins are being updated to accommodate this API change. Which will be done in a few months.

With Razorpay, you have to pay 2% no matter what kind of card you use. In fact, if you go with Razorpay enterprise paid plan that can be reduced to 0.3% to 1.88% depending on the bill amount. So, I think Razorpay is overall a great product with super bad integration and plugin support.

Anyways let me know what you think of the new plugin when you test it. Also if you find any problem in the plugin, please post the issues to that repo and not this one. As I will monitor that repo and as always Razorpay Team will pay no heed to what issues you post here. They haven't for 2 years and I don't think they ever will sadly.

**Comment by isaumya** [comment]
### Update to all
Just updated my plugin to v1.1.1 which have loads of improvements, especially in the design side so that it can be used on production site. You can check out the releases from here: https://github.com/isaumya/razorpay-gravity-forms-updated/releases

Also to know about the details of changes and to look at screenshots, check out the readme here: https://github.com/isaumya/razorpay-gravity-forms-updated

If you test out the plugin, do let me know your thoughts.

**Comment by ImPrasadM** [comment]
Hi @isaumya,
I am satified with this plugin, Because I am attaching this plugin to my application, it works fine with Payment Successful test case. Can you give me a solution for Payment Failure? There is no option available in current plugin.

Thank you

**Comment by isaumya** [comment]
@ImPrasadM Are you talking about my plugin or this plugin developed by the Razorpay Team? If you are talking about my plugin then in case of payment failure, the Razorpay popup will show payment failed and asked the user to retry. If he retries and makes the payment all goes well. If he closes the razorpay popup, the entry remains in Processing status and as soon as the user closes the razorpay popup, it goes back to the form with a fresh reload.

Also in future, if you have any questions or issues with my plugin please open issue on my repo and not this one as this repo is under Razorpay and I do not monitor it always. So, better to keep the questions related to my plugin in my plugin repo URL.

**Comment by prem-techchefs** [comment]
Added feature in latest version. You can select option to getting email notification after payment or before payment.

**Comment by isaumya** [comment]
@prem-techchefs Thanks for working on it. Please take a look at my repo. I've also improved the design of the payment process vastly which is still missing in the official plugin. It would be great if any of you guys take a look at my implementation and get some inspiration of it to make the flow smoother.
