### ISSUE TITLE
Can't Activate the plugin. Invalid Header

### ISSUE THREAD

**Issue by seherkdc** [razorpay/razorpay-gravity-forms#27]
I installed the plugin from WordPress repository and when I clicked on Activate it displayed the following WordPress error: "The plugin does not have a valid header"

**Comment by prem-techchefs** [comment]
@seherkdc  Have you installed gravity form plugin. This plugin has dependency on gravity form. But if still you are facing issue that please share the screenshot of installed plugin.

**Comment by muthumahendran** [comment]
![WordPress › Error](https://user-images.githubusercontent.com/15136383/76636561-4add1700-656f-11ea-9c67-de05734045ef.png)

**Comment by ramth05** [comment]
@muthumahendran , which version of PHP your site hosted on? This looks like your are still using unsupported version of PHP.

**Comment by muthumahendran** [comment]
@ramth05, PHP 5.6.41

**Comment by ramth05** [comment]
> @ramth05, PHP 5.6.41

@muthumahendran , we have just relased new version 1.2.1 with fix, please try to test it.

**Comment by muthumahendran** [comment]
Thank You :)

**Comment by muthumahendran** [comment]
> > @ramth05, PHP 5.6.41
> 
> @muthumahendran , we have just relased new version 1.2.1 with fix, please try to test it.

Are you have any documentation? How to redirect Razorpay payment gateway when I submit the form?
