### ISSUE TITLE
Require Documentation

### ISSUE THREAD

**Issue by muthumahendran** [razorpay/razorpay-gravity-forms#30]
Are you have any documentation? How to redirect Razorpay payment gateway when I submit the form?

**Comment by ChetanGN** [comment]
@muthumahendran We were passing the redirect URL in the action of the order form. If you want to redirect to some other page, kindly update the URL.

**Comment by prem-techchefs** [comment]
@muthumahendran  we hope this solution work for you. If you need further assistance please feel free to post here. As of now we are closing this issue.
