### ISSUE TITLE
How to show complete payment in Gravity Entries

### ISSUE THREAD

**Issue by itsachalsingh** [razorpay/razorpay-gravity-forms#31]
Hello Sir,

Can you tell me how i show the complete payment and faild payment in gravity form entries

Thanks

**Comment by ramth05** [comment]
@itsachalsingh , you can implement these 2 hooks action to achieve it. 
1. **gform_razorpay_fail_payment** with **2** params **($entry, $feed)**.
2. **gform_razorpay_complete_payment** with **4** params **( $transaction_id,
                $amount, $entry, $feed)**.

**Comment by prem-techchefs** [comment]
@itsachalsingh  We hope this steps will work for your issue. If you need further assistance please post here. As of now we are closing this issue.
