### ISSUE TITLE
Razorpay for Gravity form needs an update

### ISSUE THREAD

**Issue by alexdsgn05** [razorpay/razorpay-gravity-forms#36]
So I found this error while scanning for PHP compatibility issue.
/plugins/razorpay-gravity-forms/trunk/razorpay-sdk/src/Resource.php
9 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS).

Kindly update.

**Comment by harman28** [comment]
We've been [aware of this](https://github.com/razorpay/razorpay-php/issues/37) for some time but haven't been able to pick it up yet. I'm closing this issue for now, but we'll take up the Razorpay PHP SDK for an update later this month. Thanks for pointing this out.
