### ISSUE TITLE
Beta release improvements

### ISSUE THREAD

**Issue by mayankamencherla** [razorpay/razorpay-gravity-forms#5]
- [x] Improve landing page (confirmation page)
- [x] Redirect to failure page on cancellation

Add any other points that customers share as feedback.

**Comment by mayankamencherla** [comment]
@captn3m0 Got it to work using Paypal's redirect flow. They hook the `wp` action to a method called `maybe_thankyou_page`:

```
add_action( 'wp', array( 'GFRazorpay', 'maybe_thankyou_page' ), 5 );
```

Doing the same thing and it works for the thank you page.

**Comment by mayankamencherla** [comment]
<img width="1280" alt="screen shot 2017-12-07 at 6 56 38 pm" src="https://user-images.githubusercontent.com/18058797/33717568-63a3d48e-db80-11e7-85e9-affb461e6ae7.png">

**Comment by mayankamencherla** [comment]
Changing display message based on cancellation / payment failure / signature failure etc.

**Comment by prem-techchefs** [comment]
@mayankamencherla you can use `gform_razorpay_complete_payment` hook for handling the failure case and add custom action/page by using this hook. Please let us know if you need any further assistance.
