### ISSUE TITLE
RazorPay feed being executed with every form and giving 500 error on site

### ISSUE THREAD

**Issue by jaideep-bishnoi** [razorpay/razorpay-gravity-forms#8]
We are getting 500 error with every form submission
these are the error logs
`2018/02/02 13:09:52 [error] 22467#22467: *14943 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Razorpay\Api\Errors\BadRequestError: The amount must be at least 100. in /home/serverguy/public_html/wp-content/plugins/razorpay-gravity-forms-master/razorpay-sdk/src/Request.php:120
Stack trace:
#0 /public_html/wp-content/plugins/razorpay-gravity-forms-master/razorpay-sdk/src/Request.php(90): Razorpay\Api\Request->processError(Array, 400, Object(Requests_Response))
#1 /public_html/wp-content/plugins/razorpay-gravity-forms-master/razorpay-sdk/src/Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response))
#2 /public_html/wp-content/plugins/razorpay-gravity-forms-master/razorpay-sdk/src/Entity.php(59): Razorpay\Api\Request->request('POST', 'https://api.raz...', Array)
#3 /public_html/wp-content/plugins/razorpay-gravity-forms-master/razorpay-sdk/src/Entity.php(15): Razorpay\Api\Entity->request('POST', 'orders/', Array)
`

**Comment by Mayur-Wadpalliwar** [comment]
The exact issue is that Razorpay is getting executed even for non-payment gravity forms

**Comment by mayankamencherla** [comment]
Fixed the issue on the merchant's ftp server. Closing the issue.
